### ISSUE TITLE
Overflowing a 4 byte integer in mfi_getv (in ic.f)

### ISSUE THREAD

**Issue by makavakh** [Nek5000/Nek5000#238]
The problem is here:
`nread = nxyzr*nelr/lrbs`
`nread` is a 4 byte integer, but in my case `nxyzr*nelr` was much larger than a 4 byte integer can hold. It was assigning a wrong value to `nread` and  later crashing when `lim_chk` was called.
A simple (but hacky) solution is to have a different variable `nread8` defined as `integer*8`, calculate:
`nread8 = nxyzr`
`nread8 = nread8*nelr`
`nread8 = nread8/lrbs`
To make sure that a correct value is assigned to `nread8` and then
`nread = nread8`

**Comment by stgeke** [comment]
You are reading files larger than 4GB per MPI rank?

**Comment by fischer1** [comment]
I think the issue was simply that an intermediate value in the computation
exceeded 2B :


  nread = nxyzr*nelr/lrbs


Here, the product (nxyzr*nelr) can be large, before it is divided by lrbs.


I'd normally suggest doing the divide first, but I'm not 100% certain of the

rouding / mod() consequences with integer divide in this particular spot in

the code.


Paul


________________________________

**Comment by pschlatt1** [comment]
we had a similar issue with exactly that line in ic.f. Our solution was essentially what was suggested at first:

nread = int(  int(nxyzr,8)*int(nelr,8)/int(lrbs,8)  ,4)

which worked for us, but of course is just a tweak. Not sure whether int(XXX,8) is standard-compliant though.
Philipp

**Comment by stgeke** [comment]
* how can the result (nxyzr*nelr) overflow if nelr is < 100'000 per rank (larger numbers will exceed the available memory on most systems)
* int(x,8) is not F77 compliant

**Comment by stgeke** [comment]
My comment only holds if you read from multiple fld-files, such that nelr (per file) is say <100'000. This might not be the case. I'll fix it.

**Comment by stgeke** [comment]
#240

**Comment by makavakh** [comment]
I was reading a single large file (more than 3M elements with lx1=8) and wanted to write multi-file output. So this was done without MPIIO. In my case nxyzr*nelr was more than 4 billion.

**Comment by makavakh** [comment]
Yes, the problem was the intermediate value was larger than what 4 byte integer can hold. Dividing first won't work for some cases because integer division can simply give zero.

**Comment by stgeke** [comment]
That's why. For performance reasons I would use multiple fld files or MPIIO for dumping and reading.

On 27 Mar 2017, at 19:58, makavakh <notifications@github.com <mailto:notifications@github.com> > wrote:

I was reading a single large file (more than 3M elements with lx1=8) and wanted to write multi-file output. So this was done without MPIIO. In my case nxyzr*nelr was more than 4 billion.

**Comment by makavakh** [comment]
I know but that file was generated by g2gi and I had to read it in and then switch to the multi-file format.

**Comment by stgeke** [comment]
#258
