### ISSUE TITLE
makenek seems to not notice SIZE dependency anymore ?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#267]
Hi,

When I edit SIZE, then

makenek blah

should recompile all dependent .f files, but it doesn't do this anymore.

**Comment by RonRahaman** [comment]
I think I see what this issue is.  In makefile.template, the rule for rebuilding the Fortran objects when SIZE changes is:
``` makefile
 $(NOBJS_F) : SIZE
```
Prior to PR #258, the variable `$(NOBJ_F)` was set to be all the Fortran objects.  However, after PR #258, `$(NOBJ_F)` is no longer set to anything.  I'll revert that particular change right now.

**Comment by RonRahaman** [comment]
Fixed by @stgeke
