### ISSUE TITLE
ICEM support for exo2nek 

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#280]
@ggiannako Can we support both CUBIT and ICEM with exo2nek

**Comment by ggiannako** [comment]
In principle yes, only minor modifications will be needed to support ICEM as well. However, as far as I know, there is a bug in ICEM when exporting hex27 elements to exodusII files that requires the mesh to be loaded into CUBIT and re-exported to exodus...

@emerzari: do you know if this is fixed in the latest ICEM version?
