### ISSUE TITLE
makenek clean should clean.... 

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#338]
[ I realize there is a clean clean, but this is contrary to users' expectations ]
... this from Kento...

Prof. Fischer:

The following is the steps I took to try to get Nek working with Blue Waters:

- I first compiled with cray and realized that it doesn't work
- switched to pgi
- ran `makenek clean; makenek eddy_uv`
- it resulted in linking errors

The problem is that when I run `makenek clean`, it doesn't clean gslib. So when I try to compile with pgi, gslib's .o files are still expecting to be linked to cray's library and fails to find the appropriate routines in pgi's library. When I run `make clean` in $SOURCE_ROOT/3rd_party/gslib/src and compile again, the code compiles and runs without any problems.

My question is: how should the makenek script handle cases like this (when the user switches compilers). Should the user be expected to understand the incompatibility issue? Or should makenek detect that the user is using a different compiler than last time and automatically recompile gslib? Please let me know your thoughts on this.

Sincerely,
Kento

**Comment by stgeke** [comment]
Most compilers are linking compatible so there should be no issue.
Run 'makenek realclean' to recompile everything (including all 3rd party libs - for now it is just gslib).

**Comment by stgeke** [comment]
I think we need two existing options:

* makenek clean: compile all nek5000 source
* makenek realclean: compile all including 3rd party source 

A single clean is not very convenient as recompiles (potentially) a lot of stuff which was not changed. This wastes my time ;)

**Comment by fischer1** [comment]
Hmmmm.....

This is not an uncommon situation, however.

I've also had exactly the same problem.

I almost never user "makenek clean" .... Since makenek checks SIZE for dependencies,
makenek clean is saved for those special situations when you really want it "clean"

Our build time is not so onerous that this is an issue, and our build time should never be
so onerous that this is an issue, so it seems to me that having makenek clean do the honorable thing and actually "clean" is the right way to go.

Otherwise, unsuspecting users such as Kento and myself, who are not naive, can waste days or hours not knowing the magic keyword, real clean --- instead, we end up ripping out the repo and reinstalling, which really is too heavy.

**Comment by stgeke** [comment]
How about the following: "makenek clean" will ask you if you want to wipe off the 3rd-party stuff. This way it's fully transparent to the user.

**Comment by hackljf** [comment]
While I appreciate that having gslib keep its object code unchanged is a very common use case, it has been a very serious problem for users of Lawrence Livermore's HPC systems because that site uses networked /home mounted on a wide variety of different supercomputers. I need to "rip out" gslib (I just learned about "realclean" today) and recompile everything every time I change a single case on any host. It is now to the point where I need source code to live in scratch space on each host to avoid link errors with stale gslib, which is simply a terrible way of doing supercomputing (although github does make it easier). I see the wisdom of having 3rd_party sort of double as a "lib/" directory, but argue that the user should have the option of keeping ALL object code live $CASE/obj/ since LLNL isn't the first place (and may not be the last place) to inflict networked /home on its users. I will program an alternative and propose it at some point.

**Comment by stgeke** [comment]
Now makenek asks the user if we wants to clean all 3rd-party objects as well.
