### ISSUE TITLE
Stale URL to CVODE download

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#382]
Some collaborators are reporting that the CVODE install currently fails.  It looks like the URL for the CVODE download in 3rd_party/cvode/install is stale:

https://github.com/Nek5000/Nek5000/blob/4f97f68071b024de14574dd50e7cc5d9acbabfc3/3rd_party/cvode/install#L5

When I run that command on the command line, the download fails.  

It looks like v2.9 is not archived on the [CVODE website](https://computation.llnl.gov/projects/sundials/sundials-software).  Right now, seems like we have the option to downlad v2.7 or v3.0.  I verified that `wget` works for both of them.  

cc: @hackljf

**Comment by stgeke** [comment]
I just submitted a PR (#383) with an updated install script which I did not merge yet as all CI tests fail (because download of CVODE fails)

@RonRahaman Can you please do the following:
* make Travis use the new CVODE install script (see my PR)
* compile and install CVODE only for short_test using CVODE (currently we do this for every short_test )

**Comment by RonRahaman** [comment]
I addressed those two bullets, but I'm still getting some errors.  Could you take a look?
https://github.com/RonRahaman/Nek5000/tree/cvode-install
https://travis-ci.org/RonRahaman/Nek5000/jobs/282996769

**Comment by stgeke** [comment]
It looks like we do not link against CVODE. In my PR #383 I do this automatically depending on PPLIST. This assumes that the CVODE libraries are located in 3rd_party/cvode/lib. That's the default location of  the install script  3rd_party/cvode/install.

**Comment by stgeke** [comment]
Fixed in #385
