### ISSUE TITLE
genmap problem with intel

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#434]
All tests with intel fail most probably due to -shared-intel flag. There is linking problem
byte.c:(.text+0x165): undefined reference to `__intel_sse2_strcpy'

**Comment by stgeke** [comment]
What tests are you talking about?

-----Original message-----

**Comment by stgeke** [comment]
Oh your are talking about our tests on Jenkins. The problem is related to the fact that different compilers are used to compile genmap (see below). Make sure the env-vars FC and CC are correct. Also please import Nek5000 short_test/lib to make it compatible with the latest changes. 

----------------------
Make genmap...
----------------------
make[1]: Entering directory `/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/int/TEST_CASE/ThreeDBox/Nek5000/tools/genmap'
/usr/bin/gfortran -c -DMAXNEL=100000 -cpp -mcmodel=medium -fdefault-real-8 genmap.f

/soft/apps/packages/mpich-3.2-intel17-initial/bin/mpicc -c  -DUNDERSCORE -mcmodel=medium ../../core/byte.c
/usr/bin/gfortran -DMAXNEL=100000 -cpp -mcmodel=medium -fdefault-real-8 -o /sandbox/jenkins-ci/workspace/Nek5000/COMPILER/int/TEST_CASE/ThreeDBox/Nek5000/bin/genmap genmap.o byte.o
