### ISSUE TITLE
Why do we filter pressure for PnPn?

### ISSUE THREAD

**Issue by kmittal2** [Nek5000/Nek5000#438]
Why do we currently filter pressure for PnPn calculations?

**Comment by stgeke** [comment]
Where in the code are we doing this?

-----Original message-----

**Comment by kmittal2** [comment]
Line 104,105 in navier5.f:

**Comment by stgeke** [comment]
Hmm ... not sure. @ananiast?

**Comment by stgeke** [comment]
Input from @ananiast: There is no reason not to filter the pressure with 
Pn-Pn. Since the velocity is filtered and loses the last 2-3 modes the same can hold
for the pressure, there is no exact theory about this (maybe Paul can tell us more?)
For Pn-Pn-2 though the pressure order is already lower by 2 degrees so it should 
not be filtered.

**Comment by fischer1** [comment]
My general feeling has been that it's better to not filter the pressure.
Ketan had a case, however, where there was high wavenumber content
in the pressure that was readily cleaned up by the filter.   We'll look into
it.

**Comment by pschlatt1** [comment]
In my understanding the role of the pressure in incompressible flow is quite special as a Langrange multiplier, so filtering the pressure might break this. Not being too familiar with PnPn, perhaps there are some additional arguments why it should be used anyway. However, filtering the pressure every once in a while in order to remove noise is certainly ok.
