### ISSUE TITLE
Type error for mod(int(8), int)

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#470]
The IBM XL compiler for POWER8 expects the arguments to `mod` to be the same type.  Here, we are comparing an `int(8)` and an `int`, and the compiler raises a fatal error.  

https://github.com/Nek5000/Nek5000/blob/375227de0b87792d0eabd6a07cb927e39a2bac06/core/reader_re2.f#L181

It can be fixed by explicitly casting:
``` Fortran
do i = 0,mod(nrg,int(np,8))-1
```
I also tried to see if there was a compiler flag to suppress the error, but I couldn't find one.

**Comment by RonRahaman** [comment]
Also occurs here:
https://github.com/Nek5000/Nek5000/blob/375227de0b87792d0eabd6a07cb927e39a2bac06/core/reader_re2.f#L288

**Comment by stgeke** [comment]
Yes this  something we need to fix. The casting is not F77 compliant.

On 31 Jan 2018, at 17:22, Ron Rahaman <notifications@github.com <mailto:notifications@github.com> > wrote:

The IBM XL compiler for POWER8 expects the arguments to mod to be the same type. Here, we are comparing an int(8) and an int, and the compiler raises a fatal error.

https://github.com/Nek5000/Nek5000/blob/375227de0b87792d0eabd6a07cb927e39a2bac06/core/reader_re2.f#L181

It can be fixed by explicitly casting:


do i = 0,mod(nrg,int(np,8))-1

I also tried to see if there was a compiler flag to suppress the error, but I couldn't find one.

**Comment by trudeaun** [comment]
@RonRahaman Which compiler are you using, is it `IBM XL Fortran for Linux V15.1.6`? Are you getting this as your error: `1513-041 (W) Arguments of the wrong type were specified for the INTRINSIC procedure "mod".`?

About suppressing diagnostic messages, it is possible on warning (W) and informational (I) messages, see [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SSAT4T_15.1.6/com.ibm.xlf1516.lelinux.doc/compiler_ref/suppr.html). If the error raised is the one I mention, you can use `-qsuppress=1513-041` to suppress it.

**Comment by RonRahaman** [comment]
@trudeaun, that is all correct.  I'm using IBM XL Fortran for Linux on OLCF's Summitdev, and that is the error message I received.  I'll try using `-qsuppress=1513-041`.  Thanks!
