### ISSUE TITLE
gfortran 8.1 fails to compile

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#497]
Compilation fails as we are passing arguments containing too few elements for a dummy argument. Here is an example:

```
subroutine foo(a,b)
real a(1)
call foo2(a)
return
end

subroutine fo2(c)
real c(lx1*ly1*lz1)
...
return
end
```

We do this quite frequently in the code. 

To fix this we have two options:
- change to assumed size array e.g. `real a(*)`
- compile with `-std=legacy`

**Comment by pschlatt1** [comment]
I would prefer assumed size arrays. We have seen a similar issue for the Cray compiler which produced wrong results when full optimisation was on. using assume size arrays fixed it, if I recall well.

**Comment by stgeke** [comment]
Agreed but it may take a while to do this (a lot of code needs to be changed). In the meantime I'll add the compilation flag. Is the Cray compiler issue #430 fixed?

**Comment by fischer1** [comment]
I would propose that we put in the desired value, e.g.,

      subroutine foo(a,b,n)
      real a(n), b(n)

      do i=1,n
           a(i) = func of b(i)
       enddo
       return
       end

If there are routines where this is not clear, then we can use a(*)

Note that there are some openacc() instances where it does not like passing
a scalar into such a routine (i.e., n=1 case).  For example, 

       s=glsum(s,1)

seems to cause some difficulties.  In this case, the issue is:  where does the
input "s" reside??   Host?  Or device?

It is a perfectly valid and correct use of glsum.   We could, however, develop
a scalar ("host-oriented") implementation, of the form:

       s=glsum_host(s)

or 
      s=glsum_sc(s)

...

**Comment by misunmin** [comment]
Yes that would be my preference too while openacc requires the length.

________________________________

**Comment by fischer1** [comment]
Incidentally,

In your foo example, there is nothing really wrong (of course)---and it seems to me
that the hard-coded parameter-based array declaration must be ok---it should perform
fast because the compiler is being told how big the array is.

The rest is merely a pointer to memory...

So, what I'm saying is that I wouldn't want to do is to replace "real a(lx1*ly1*lz1)"  with "real a(*)"

I cannot see how the latter could be more informative to the compiler.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/b635b29f681617eceda3a8b11abb47e8c4ac2253
