### ISSUE TITLE
maketools gives up too easily

### ISSUE THREAD

**Issue by dshaver14** [Nek5000/Nek5000#624]
maketools should try to move on to the next entry in $LIST when building a tool fails rather than quitting altogether.

**Comment by stgeke** [comment]
This way you typically miss that some tools were not successfully compiled. Note, you can always compile a custom list of tools e.g. `./maketools genbox genmap`.

**Comment by fischer1** [comment]
However, I agree with Dillon --


Can we make it so that nek basic tools are compiled first, e.g.,


genmap

genbox

prex

postx


then others?


It's frustrating to be walking someone through the workflow and find that we have to go back and do


maketools genbox

maketools genmap


because maketools all failed somewhere.


It also sows doubt in their mind about the viability of nek in general.


Thanks!


________________________________

**Comment by stgeke** [comment]
Resolved in https://github.com/Nek5000/Nek5000/commit/d655ade117732b8625532fdecf1f17f5b1ab11e7
