### ISSUE TITLE
Broken Cyclic BC 

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#627]
> https://groups.google.com/forum/#!topic/nek5000/e6yZg_-ojPs
> https://groups.google.com/forum/#!topic/nek5000/LD7AMNqAWL8

**Comment by flowflaw** [comment]
I have attached a simple test case with broken cyclic BCs (see attached screenshot). It might help with verification/debugging. The test case uses a box mesh, warped it into an annulus in usrdat2.
[cyclic.zip](https://github.com/Nek5000/Nek5000/files/3276359/cyclic.zip)
![cyclic](https://user-images.githubusercontent.com/45652139/59270441-c103c480-8c51-11e9-8997-5978707fe2f5.png)

**Comment by stgeke** [comment]
Please use our mailing list for requests like this.

On 11 Jun 2019, at 15:05, flowflaw <notifications@github.com <mailto:notifications@github.com> > wrote:

I have attached a simple test case with broken cyclic BCs (see attached screenshot). It might help with verification/debugging. The test case uses a box mesh, warped it into an annulus in usrdat2.
cyclic.zip

**Comment by flowflaw** [comment]
Sorry, it was not meant to be a request.

**Comment by stgeke** [comment]
I don't see anything attached to the issue?

-----Original message-----

**Comment by stgeke** [comment]
Can you please attach a small testcase.

**Comment by flowflaw** [comment]
Hi, I attached my testcase. It's a 2D annulus with walls in the radial direction and periodic BCs in the circumferential direction. I generate a box mesh and warp it into a sector of an annulus in usrdat2. I have set cyclicBoundaries = yes in the .par file. From the screenshot you can see that the periodic BCs don't work as expected. 

The initial conditions are very crude and do not match the boundary conditions since I just set ux=1 and uy=uz=0. I figure that shouldn't be a problem as long as I discard the first few timesteps.

my Nek version is 17.0 and I use GNU compilers on Ubuntu.

Thanks for your effort!

Here are the files:
![cyclic](https://user-images.githubusercontent.com/45652139/60152439-cf6ce700-97e0-11e9-89c5-3968da5bfcb0.png)
[cyclic.zip](https://github.com/Nek5000/Nek5000/files/3328293/cyclic.zip)

and here's my original thread from the forum:
https://groups.google.com/forum/#!topic/nek5000/h_D_iapxvVA

**Comment by flowflaw** [comment]
Update: I made the test case work by adding stressFormulation = yes to the .par file. I don't  fully understand what that does, but the handbook states that the no stress formulation assumes constant viscosity, so that shouldn't make a difference here, right?

**Comment by stgeke** [comment]
The stress formulation is required as soon as the velocity components are coupled.

**Comment by stgeke** [comment]
Latest repo version enables stress formulation automatically if cyclicBoundaries are present.
