### ISSUE TITLE
Fast residual projection 

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#63]
Robust but slow.

**Comment by maxhutch** [comment]
What is this issue about?

**Comment by stgeke** [comment]
@fischer1 Any chance to get this fixed with the new release?

**Comment by njansson** [comment]
Wouldn't one idea to speed things up be to remove the deep copying when evicting the oldest vector?

For example, instead of shifting all vectors one step to the left, keep track of the oldest vector and rewrite all loops wrt. that index. 

Something along the lines of 90e3d2e8ebdc1afc3bc7a8c399bba4f8965db089
