### ISSUE TITLE
Code does not compile with implicit=none

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#68]
To fix this, we need to explicitly declare all variables used in all `INCLUDE` files. 

I suggest to add a `SIZE.usr` (this file will live in user space). `SIZE`  (static file in the source) contains whatever we want to hide from the user (e.g. variable declarations or other internals). `SIZE` will include `SIZE.usr`. This is the cleanest solution I can think of and it improves the user experience (`SIZE` is less messy). 

No code changes are required. However, the user needs to use the new `SIZE.usr` template (distributed with the source). I never liked the `makenek` magic to tweak old `SIZE` files. 

Overall I do _not_ think this is a big deal as we do something similar with `makenek`.

We had a similar discussion at the user meeting.
@fischer1 @pschlatt1 What are your thoughts on that?

**Comment by fischer1** [comment]
The key step is to embed the declarations in all the INCLUDE files.

I'm not 100% certain why we need SIZE.usr ?   Can you remind me?  I recall
something like this from before --- Oh yes -- Now I know.   We need to declare
all the SIZE arrays too.

My suggested remedy:
1.  Put declarations in SIZE for all the Examples.
2.  Any existing SIZE files out there are either:
   
   (A)   They are OK because the user in question is not going to
           run IMPLICIT NONE
   
   (B)   The user in question IS going to run IMPLICIT NONE and will
           either:
   
   ```
       B.1 -- Grab a SIZE file from an example, or
       B.2 -- Modify on his own in any case.
   ```

To me, the scenarios (1) and (2) cover all SIZE issues and we don't need
an extra include into SIZE  [ unless you want to do other things in the SIZE.usr
file, such as the other appends that we currently have ].

I'm not that unhappy with what we have, for the following reason:

```
When I look at my SIZE file and see those declarations, it reminds of what
options Nek offers that I'm not currently using.

If those declarations are hidden in SIZE.usr, which I might never edit, then
I'd not be reminded of those options.
```

Paul

**Comment by stgeke** [comment]
I am ok with your suggestion although I would prefer a SIZE.usr (containing all available parameters + optional user stuff) and SIZE (containing all declarations).

**Comment by RonRahaman** [comment]
@stgeke, if you're going in this direction, then we shouldn't target the change for v16.0.0.  We should wait for the next major revision (v17.X.X) to change the interface (see http://semver.org/)

**Comment by stgeke** [comment]
I think we go with Paul's suggestion.

**Comment by pschlatt1** [comment]
I would also agree with Paul's suggestion, i.e. that the declarations are directly in the SIZE file without an additional SIZE.usr. A slightly unrelated but still relevant question is where to put the declarations in the SIZE and other INCLUDE files; should the declarations be all at the end, the beginning or close to the parameters. I would vote for the last option, even though one needs to scroll a bit more in the SIZE file.

**Comment by fischer1** [comment]
Occasionally (twice in the last 3 decades) you run into a compiler that insists
on

DECLARE

then

COMMON BLOCK..

So, I would propose (sadly) that they are at the top.   I'll try to make it properly
condensed yet readable to maximize utility.

I'll do one of these now..

Paul

**Comment by nicooff** [comment]
Hi,

Sorry for jumping in the conversation a bit late. I have my own branch with the definitions added to the include files:

https://github.com/nicooff/nek5000/tree/include_def

I am currently running all of my cases with 'implicit none' in the subroutines of the usr file and it worked fine so far. There might still be some errors or definitions missing but this could serve as a basis maybe!

There are still some issues pending though:
- The SIZE file with all declarations is not in the repo because it is not in the core folder in the master branch so I did not know where to put it... I can add it to any folder if needed.
- I did not touch MOABCORE or NEKMOAB. I am a bit unsure if it is necessary or not.
- There is a couple of variables that I do not know where to declare:
  - nfldmax, nmaxcom and nmaxl in NEKNEK
  - nsessmax in GLOBALCOM  
    Should these be parameters in the SIZE file?
- I proceeded by doing COMMON BLOCK then DECLARE unfortunately. But if you want to go on with my branch, I can spend one hour or two inverting that without problem.
- In most examples, there is a variable 'source'  in the userq subroutine. However, I could not find it in any include file. Did I miss it? If this variable is not a NEK variable, it should be removed from all the examples.

As a side note, I realized while adding definitions that several variables with the same name are declared in different include files:
- x in GMRES, NEKUSE and ORTHOSTRS
- mu in GMRES and NEKUSE
- dd in FDMH1 and SEMHAT
- zgl in SEMHAT and WZF
- (might be more)

I guess that is not a big issue but I leave it as a reference.

Best,
Nicolas

**Comment by stgeke** [comment]
That's great Nicolas!

Here are my thoughts on that:
- Let's add a SIZE template to core
- nfldmax, nmaxcom, nmaxl, nsessmax go into SIZE
- No need for MOAB, at least for now
- Yes, the declarations should go first
- Don’t know why there is a source in most userq in the examples. @fischer1 ?
- Make sure you the latest INCLUDE files from the release/v16.0.0 branch
- I think we should make the variable names exclusive, just to avoid potential problems

**Comment by fischer1** [comment]
We don't need "source" and should take it out.

**Comment by pschlatt1** [comment]
Hi

are we still aiming for the v16 release with the typing of the common blocks (see @RonRahaman comment above)? @nicooff will be away the next ten days, but then we could do all the necessary changes, is that ok?
some comments on your comments:
- yes, a SIZE template is great. "SIZE-template"?
- nfldmax, nmaxcom, nmaxl, nsessmax need to go into SIZE with standard Nek size of 1 (why 1 btw, one could do 0)
- Regarding order: Do we want:

real a
common /aa/ a
real b
common /bb/ b

OR

real a
real b
common /aa/ a
common /bb/ b
- source will be taken away once we start to put implicit none in the examples.
- yes, we should think of all the duplicate variable names, and make sure they will be exclusive. Other examples are "ktot" in ORTHO\* which we should think how to change. However, for just putting types it would not matter.

**Comment by RonRahaman** [comment]
IMO, pushing back the release date is not a problem at all.  @stgeke and @fischer1, please let us know if we actually have some external deadlines.  

We're following a frequently-used release model described [here](http://nvie.com/posts/a-successful-git-branching-model/).  In using this model, one of the most important motivating factors is **prioritizing open issues**.  Once we decide to make a new release (v16.0.0), we are only introducing **bugfixes**.  New **features** will wait until the next minor release (v16.1.0).     

Why limit ourselves like that?  As in most healthy, active projects, we have a long list of desired new features.  Periodically, it's important to put them on the back burner while we address all the actual bugs.  

Unless we have external deadlines, I think the date is just another motivating factor.  I'm perfectly happy accommodating the busy schedule of someone as hard-working as @nicooff.  What do y'all think?

**Comment by pschlatt1** [comment]
what is the targeted date for v16.0.0?

**Comment by stgeke** [comment]
I think we should aim for mid-September.

**Comment by nicooff** [comment]
Hi everyone,

I'm back to work and I am ready to finish this issue. In order to make sure that everyone agrees and to avoid overlap, here is what I plan to do before the release:
1. Add definitions to all the include files. What should be the order between common blocks and declaration? (cf. @pschlatt1 comment above). I'll also look in the Fortran77 standard if I find anything about the proper way to do it.
2. Add a SIZE file template with all declarations in the core folder (@stgeke is it still ok to do that?) and try it out with one of the examples (probably ext_cyl).

If it works fine and if everybody agrees with the changes, this can be included into the release. Then, we can add the new SIZE file and implicit none in the user files of all the examples. Finally, after the release, we plan to gradually add "implicit none" to every routine in the code.
