### ISSUE TITLE
Benard example fails w/ current Nek5000, works with version of Dec 28, 2019 (or tarball)

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#704]
The benard example is not working.

We need to re-institute testing of all examples.

**Comment by stgeke** [comment]
What do you mean by it doesn't work?

**Comment by fischer1** [comment]
ray_9 blows up in 9 timesteps.

Actually, I was wrong about it working with my Dec. 28, 2019 version... 

Checking v17.

**Comment by fischer1** [comment]
It works with v17.

**Comment by lcarasik** [comment]
Testing with all examples should be a baseline of every new install and pull request/code mod.

**Comment by emerzari** [comment]
Lane, every new commit is tested through Travis.

Paul was here referring to a case that is part of NekExamples and not part of the test suite that is run at every commit.
That Benard case should be run as part of the overnight tests on Jenkins (not on every commit because it takes too long to run all the examples every time).
This was the case at least until a while ago. We will look into this.

On Dec 30, 2020, at 11:30 AM, Lane Carasik <notifications@github.com<mailto:notifications@github.com>> wrote:



Testing with all examples should be a baseline of every new install.

**Comment by lcarasik** [comment]
Elia, I don't run Travis on my local installs. You need to properly valid system installs. It's a standard code verification practice.

NekExamples includes a lot more cases to test than shortrun. If it can't work for both, there's probably an issue.

**Comment by emerzari** [comment]
Absolutely, Please refer to README in short_tests in the tarball or in the repository folder.  You should be able to re-run the certification tests as needed.
I agree that a reference to readme and some discussion in NekDoc is good.

On Dec 30, 2020, at 11:42 AM, Lane Carasik <notifications@github.com<mailto:notifications@github.com>> wrote:



Elia, I don't run Travis on my local installs. You need to properly valid system installs. It's a standard code verification practice.

**Comment by lcarasik** [comment]
Elia, this needs to be provided to users in a meaningful format (NekDocs). You can't expect new users to be looking around short_tests if they are learning the code.

**Comment by stgeke** [comment]
https://github.com/Nek5000/NekExamples/issues/150
