### ISSUE TITLE
High order Jacobian matrix, interpolation function jgl jgt for GLL & GL interpolation

### ISSUE THREAD

**Issue by Maccchiatooo** [Nek5000/Nek5000#842]
I have some questions about GLL & GL interpolation when lx1 neq lxd. 

1. In convect.f, subroutine convop_fst_2d, we first compute lxd order gradient and compute {C dot grad(u)}. In this case, I believe Jacobian is implicitly multiplied inside of C matrix. I am wondering if I can **explicitly obtain Jacobian for lxd order**. Or **where can I find the construction of C matrix ?**

2. In the subroutine intp_rstd, we are able to transfer GLL to GL, and GL back to GLL. Now, I want to compare grad_rstd with local_grad2 when mx=md, which means lx1=lxd. It seems that the results are not consistent. While it should give the same result, because convop_fst_2d use grad_rstd to compute gradient when lx1=lxd. And I further noticed that the problem is not from dg & dgt, but from subroutine intp_rstd, and jgl & jgt. I don't know if this scheme works when mask is not used? If it works, then the gradient should be consistently computed by local_grad2 and grad_rstd. Or we have to use bmnv rather than binvm1 to evaluate B-1 C grad u?

3. In subroutine conv_fst, why ifd always true???? In subroutine grad_rstd, why `get_dgl_ptr (ip,md,md)` but not `get_dgl_ptr (ip,mx,md)`???

**Comment by fischer1** [comment]
You can find a full description of the dealiased operator here:

https://link.springer.com/article/10.1007/s10915-013-9704-1

hth,
Paul

________________________________
From: Maccchiatooo ***@***.***>
Sent: Saturday, September 28, 2024 1:26 PM
To: Nek5000/Nek5000 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nek5000/Nek5000] High order Jacobian matrix, interpolation function jgl jgt for GLL & GL interpolation (Issue #842)


I have some questions about GLL & GL interpolation when lx1 neq lxd.

  1.  In convect.f, subroutine convop_fst_2d, we first compute lxd order gradient and compute {C dot grad(u)}. In this case, I believe Jacobian is implicitly multiplied inside of C matrix. I am wondering if I can explicitly obtain Jacobian for lxd order. Or where can I find the construction of C matrix ?

  2.  In the subroutine intp_rstd, we are able to transfer GLL to GL, and GL back to GLL. Now, I want to compare grad_rstd with local_grad2 when mx=md, which means lx1=lxd. It seems that the results are not consistent. While it should give the same result, because convop_fst_2d use grad_rstd to compute gradient when lx1=lxd. And I further noticed that the problem is not from dg & dgt, but from subroutine intp_rstd, and jgl & jgt. I don't know if this scheme works when mask is not used? If it works, then the gradient should be consistently computed by local_grad2 and grad_rstd. Or we have to use bmnv rather than binvm1 to evaluate B-1 C grad u?

  3.  In subroutine conv_fst, why ifd always true???? In subroutine grad_rstd, why get_dgl_ptr (ip,md,md) but not get_dgl_ptr (ip,mx,md)???
