### ISSUE TITLE
Variable viscosity check with PNPN

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#95]
If the viscosity is spatially varying the coupled Helmholtz solver has to be used (IFSTRS=T) for PN/PN otherwise you'll get a wrong result. Currently this is not checked by the code. We may want to add a check or set IFSTRS=T by default.

**Comment by fischer1** [comment]
One cheap way to do this is compute min/max of viscosity after it is set and to set ifstrs accordingly?

I guess this raises the question:  Can we switch to ifstrs=T in Pn/Pn in the middle of the simulation?  I think the answer is Yes -- but not 100% certain.

**Comment by stgeke** [comment]
@fischer1 Instead of checking it every timestep (and turning it on if needed) we could just exit if both IFSPLIT and IFUSERVP are true?

**Comment by stgeke** [comment]
@ananiast What do you think?

**Comment by ananiast** [comment]
@stgeke @fischer1 I agree with Stefan, it is better to simply exit after reading the parameters in the case that IFUSERVP and IFSPLIT are true, with a message to the user that "If the viscosity is spatially varying (IFUSERVP=T) the coupled Helmholtz solver has to be used (IFSTRS=T) for PN/PN, otherwise you'll get a wrong result."

**Comment by stgeke** [comment]
The drawback is that we break existing user cases. I guess that's ok having in mind that you may get a wrong result without knowing.

**Comment by ananiast** [comment]
@stgeke should it be allowed to use IFSTRESS=F with PN-PN and variable properties if someone, knowing that the strain rate tensor is not correctly taken into account, still wants to do this?

**Comment by stgeke** [comment]
Can you think of a use case? I guess the user can always overrule the default settings setting the right flags in usrdat3 and/or userchk.

**Comment by ananiast** [comment]
@stgeke well this is what should be mentioned in the message then, e.g.: "EXIT because if the viscosity is spatially varying (IFUSERVP=T) the coupled Helmholtz solver has to be used (IFSTRS=T) for PN/PN, otherwise you'll get a wrong result. If you still want to use the IFSTRS=F you can overrule the default settings by setting the right flags in usrdat3 and/or userchk"

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/d52c9bd361bcadb1de6b3954c02a2a387156120f
